### ISSUE TITLE
It only work with flutter 3?  

### ISSUE THREAD

**Issue by nowjordanhappy** [Alexqwesa/app_bar_with_search_switch#1]
I'm running in flutter 2.10.3 and getting error

**Comment by Alexqwesa** [comment]
what error did you get?

**Comment by Alexqwesa** [comment]
Most likely it is because AppBar had new parameters, in new flutter versions - so, it is easy to create package which support flutter 2.10.3, but i need error log.

**Comment by nowjordanhappy** [comment]
Thank you for anwsering. I got this error

app_bar_with_search_switch: ^1.3.3

<img width="1319" alt="Screen Shot 2022-08-03 at 10 05 28" src="https://user-images.githubusercontent.com/26355419/182642463-88ce9adb-185a-4a12-ba06-e9501b189343.png">

**Comment by Alexqwesa** [comment]
try:
app_bar_with_search_switch: ^1.3.5

The release 1.3.5 is a special release with support of old flutter sdk, it tested with flutter 2.10.0

**Comment by nowjordanhappy** [comment]
Thank you so much. Still getting the error.

<img width="1368" alt="Screen Shot 2022-08-04 at 00 59 48" src="https://user-images.githubusercontent.com/26355419/182773945-ae10d834-70c3-4bed-9909-2cc25ba89684.png">

**Comment by nowjordanhappy** [comment]
You can check my fork the version 1.3.3, I fixed https://github.com/nowjordanhappy/app_bar_with_search_switch/tree/flutter_v2

I don't pull request in case something is missing.

**Comment by Alexqwesa** [comment]
> Thank you so much. Still getting the error.
> 
> <img alt="Screen Shot 2022-08-04 at 00 59 48" width="1368" src="https://user-images.githubusercontent.com/26355419/182773945-ae10d834-70c3-4bed-9909-2cc25ba89684.png">

you used version 1.3.6 here

use exact version 1.3.5
**app_bar_with_search_switch: ^1.3.5**

The release 1.3.5 is a special release with support of old flutter sdk, it tested with flutter 2.10.0, and **it is the only release that support old flutter versions**, release 1.3.6 didn't support old versions...

**Comment by Alexqwesa** [comment]
close as resolved, if you still have the issue, please open issue again
