### ISSUE TITLE
Change Textfield color?

### ISSUE THREAD

**Issue by jufry-a** [Alexqwesa/app_bar_with_search_switch#2]
How to change the color of Textfield. The text become dark with dark background too when Dark Theme activated. it makes the eyes uncomfortable.

**Comment by Alexqwesa** [comment]
you could have used `title: ` parameter of `AppBarWithSearchSwitch` for full customization of text field, 
but i think it is better if I just change default values....

check version 1.4.0 (2.0.0-dev.6) - it should be fixed
>> v1.4.0 fix dark theme: use theme.appBarTheme colors as default and fallback to theme.canvasColor (which was used before)

now try to set 
```
theme.appBarTheme.foregroundColor 
theme.appBarTheme.backgroundColor
 ```

sorry for delay...
