### ISSUE TITLE
[Feature request] Animation for Search app bar activation

### ISSUE THREAD

**Issue by philitell** [Alexqwesa/app_bar_with_search_switch#3]
As listed in your TODOs "Animation for Search app bar activation" would be a great feature.
It would be fantastic to be able to use an animation like this one here: https://pub.dev/packages/animation_search_bar

Thanks for your work - great package!

**Comment by Alexqwesa** [comment]
thanks for reminder, working on it)... feature is coming soon

**Comment by Alexqwesa** [comment]
Done in versions **1.5+** and **2.0.0-dev.7+**

* added AppBarWithSearchSwitch.**animation** parameter, which can be used for any **custom animation**,
also there are two ready to use animations: [AppBarAnimationSlideLeft], [AppBarAnimationSlideDown].

Here is current documentation for [AppBarWithSearchSwitch.animation](https://pub.dev/documentation/app_bar_with_search_switch/latest/app_bar_with_search_switch/AppBarWithSearchSwitch/animation.html)

**Comment by Alexqwesa** [comment]
I will experiment with different animations in order to select a nice one - and set it as default...

**Comment by Alexqwesa** [comment]
I decide not to use animation by default, if someone want animation - just use these parameters:

[AppBarWithSearchSwitch.animation](https://pub.dev/documentation/app_bar_with_search_switch/latest/app_bar_with_search_switch/AppBarWithSearchSwitch/animation.html)
[AppBarWithSearchSwitch.animationOfSpeechBar](https://pub.dev/documentation/app_bar_with_search_switch/2.0.0-dev.14/app_bar_with_search_switch/AppBarWithSearchSwitch/animationOfSpeechBar.html)

they both support:

- custom animation,
- and ready to use animations: [AppBarAnimationSlideLeft], [AppBarAnimationSlideDown].
