### ISSUE TITLE
AppBarwithSearchButton have error all show underline

### ISSUE THREAD

**Issue by william150823** [Alexqwesa/app_bar_with_search_switch#5]
appBar: AppBarWithSearchSwitch(
              closeOnClearTwice: false,
              clearOnClose: true,
              showClearButton: true,
              keepAppBarColors: true,
              searchInputDecoration: InputDecoration(
                border: InputBorder.none,
                hintText: 'hint.search'.tr,
                hintStyle: TextStyle(fontSize: 12.sp),
                floatingLabelBehavior: FloatingLabelBehavior.never,
              ),
              titleTextStyle: TextStyle(fontSize: 11.sp),
              clearSearchIcon: Icons.close,
              customIsSearchModeNotifier: controller.isSearchMode,
              customTextNotifier: controller.searchText,
              onChanged: (value) {
                controller.onSearchChange(value);
              },
              onCleared: () {
                //
              },
              onClosed: () {
                //
              },
              appBarBuilder: (_) => CustomAppBar(
                    title: 'title.group_create'.tr,
                    actions: const [
                      AppBarSearchButton(
                          changeOnlyOnSubmit: true, buttonHasTwoStates: false),
                    ],
                  )),
                  
                  
May I know how to update the AppBar title with onChanged --> value? This occur when I update my Flutter SDK to 3.16.0

https://github.com/Alexqwesa/app_bar_with_search_switch/assets/151737266/c2dbd601-c83c-4e02-b93b-d3089c504b5b

**Comment by Alexqwesa** [comment]
yes, it happen because of Flutter SDK to 3.16.0,

currently, this should help you: 
`keepAppBarColors: false,`

working on it....

**Comment by william150823** [comment]
Hi @Alexqwesa appreciate your reply and, it is working well. Thanks for your assist. 

https://github.com/Alexqwesa/app_bar_with_search_switch/assets/151737266/8b2511ea-4bc3-4979-abb2-04070f5872f4

**Comment by Alexqwesa** [comment]
Should be fixed in: [1.7.0](https://pub.dev/packages/app_bar_with_search_switch) / and: [2.0.0-dev.17](https://pub.dev/packages/app_bar_with_search_switch/versions/2.0.0-dev.17)
