### ISSUE TITLE
Text Style on SearchInputText

### ISSUE THREAD

**Issue by arcas0803** [Alexqwesa/app_bar_with_search_switch#7]
Hi!

Amazing work of this package.

Can you add the option to pass Text Style for the search input text to handle style of the input text? 

Thanks

**Comment by Alexqwesa** [comment]
in version 1.6.2:
[AppBarWithSearchSwitch].titleTextStyle now also applied to default TextField (in search mode),

did you tried it?

**Comment by arcas0803** [comment]
I havent, but i want diferent styles between title and search 

If it's not possible it's ok

**Comment by Alexqwesa** [comment]
> I havent, but i want diferent styles between title and search

`appBarBuilder:`  - is where you create default AppBar(),

The `titleTextStyle` and other parameters of `AppBarWithSearchSwitch` is for search mode.

```
  /// This parameter is used then search is active: [isSearchMode] == true.
  ///
  /// It is applied to default [TextField] that shown when [isSearchMode] == true.
  final TextStyle? titleTextStyle;
```

**Comment by arcas0803** [comment]
Ok nos i understand.  Thanks formthe explanation, and sorry if i made you loose time.

I close this as resolve

**Comment by arcas0803** [comment]
Solved
