### ISSUE TITLE
Allow custom FocusScope / Auto Focus on start search mode

### ISSUE THREAD

**Issue by dickermoshe** [Alexqwesa/app_bar_with_search_switch#8]
Thoughts?

**Comment by Alexqwesa** [comment]
Can you please provide more details about what you are exactly suggesting?

or just explain your usecase...

**Comment by dickermoshe** [comment]
an option that entering search mode the auto focus the text field or allow to set  a focus scope on the text field without overriding the title builder, then I could listen for isSearchMode and request focus when is goes from false to true.

**Comment by Alexqwesa** [comment]
I only test android (API 33) and linux - autofocus work with mouse, but it didn't work with keyboard(...    I send commit with FocusNode code to GitHub(i hope it will fix issue), and I will update package soon...

**Comment by Alexqwesa** [comment]
v1.8.3  -  autofocus works( as it should have been ), 

if someone want to use custom title, you can also use [searchFocusNode](https://pub.dev/documentation/app_bar_with_search_switch/latest/app_bar_with_search_switch/AppBarWithSearchSwitch/searchFocusNode.html) (that will activate then search is triggered) - here is updated example for [AppBarWithSearchSwitch.title](https://pub.dev/documentation/app_bar_with_search_switch/latest/app_bar_with_search_switch/AppBarWithSearchSwitch/title.html)     -     new line `focusNode: mainWidget.searchFocusNode,`


update for version 2+ coming soon

**Comment by dickermoshe** [comment]
This is awesome.
So many packages on pub are broken and aren’t maintained.
This is an awesome departure from that.
Looking forward to using this all over and seeing what else you create!
